# -*- coding: utf-8 -*-
"""process_ml_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16d0JfZE91_r6m5j71ZtJAKN51sLlvj-L
"""

import pandas as pd
import numpy as np
from pathlib import Path

current_dir = Path(__file__).parent

"""Getting the data saved from the fetch"""

fetch_csv_path = current_dir.parent.parent/ "csv" / "Google" / "completerawdata.csv"

df_raw = pd.read_csv(fetch_csv_path)

df_raw['date']= pd.to_datetime( df_raw['date'])

"""im gonna add the day of the week  because some stock can have some behavior based on the day of the week"""

df_raw['day_of_week']= df_raw['date'].dt.day_of_week

"""i also need to get rid of the bollinger upper bands and instead calculate the bollinger width"""

df_raw['day_var_range']= (df_raw['high']-df_raw['low'])/df_raw['close']
# to make it relative
df_raw =df_raw.drop('high', axis=1)
df_raw =df_raw.drop('low', axis=1)

df_raw['OBV'] = np.sign(df_raw['OBV']) * np.log1p(np.abs(df_raw['OBV']))
df_raw['volume']= np.log1p(df_raw['volume'])

"""Here im creating some features based on the one fetched"""

#--- calculate BBands width----#
df_raw['Bband_width']= (df_raw['Real Upper Band']-df_raw['Real Lower Band'])/df_raw['WMA']
df_raw =df_raw.drop('Real Lower Band', axis=1)
df_raw =df_raw.drop('Real Upper Band', axis=1)

df_raw['day_diff'] = (df_raw['close']- df_raw['open'])/df_raw['open']
df_raw= df_raw.drop('open', axis = 1)

"""we can see via the correlation matrix that the rsi eand the cci will be really useful in this dataset , the correlation between the real midle band and the wma is really high : they mesure the same stuff ican get rid of one"""

df_raw = df_raw.drop('Real Middle Band', axis =1)

"""slok and rsi give the same information i will get rid of slowk & i will get rid of the shares numbers as they are equivalent to the volume"""

df_raw = df_raw.drop('MACD', axis =1)

df_raw = df_raw.drop('shares_outstanding_basic', axis =1)

df_raw = df_raw.drop('SlowK', axis =1)

df_raw['ATR']= pd.Series.rolling(df_raw['day_var_range'], window=10).mean()
df_raw['ATR'] = df_raw['ATR'].fillna(method='bfill').fillna(method='ffill')

"""testing some enhancements over here :
maybe the stock can have an behavior based on the day of the week i will do it in a cyclic way for the Ml model
"""

df_raw['day_cos'] = np.cos(2 * np.pi * df_raw['day_of_week'] / 7)

df_raw= df_raw.drop('day_of_week', axis=1)

df_raw =df_raw.drop('date', axis=1)

df_xgboost = df_raw.copy()

"""Here i am creating some lagged features so the xgboost model will have ann access to some time of time series behavior"""

#lag 1 to 5
lag_features = ['close', 'volume', 'RSI', 'ADX', 'MACD_Signal',
                    'MACD_Hist', 'CCI', 'SlowD', 'OBV', 'day_var_range',
                    'Bband_width', 'day_diff']

for feature in lag_features:
        if feature in df_raw.columns:
            for lag in range(1, 6):
                df_xgboost[f'{feature}_lag{lag}'] = df_xgboost[feature].shift(lag)

df_xgboost = df_xgboost.fillna(method='bfill').fillna(method='ffill')

df_normalizedLSTMdata = df_raw.copy()

# cols_to_exclude = ['date', 'up_down']
# cols_to_normalize = [col for col in df_normalizedLSTMdata.columns if col not in cols_to_exclude]
# scalerLSTM = StandardScaler()
# df_normalizedLSTMdata[cols_to_normalize] = scalerLSTM.fit_transform(df_normalizedLSTMdata[cols_to_normalize])

df_normalizedXGBoost = df_xgboost.copy()

corr_lstm = df_normalizedLSTMdata.corr()

df_normalizedLSTMdata['target']= np.where(df_normalizedLSTMdata['close'] > df_normalizedLSTMdata['close'].shift(1), 1,0)

print("ANALYSIS OF TARGET DISTRIBUTION")
target_dist = df_normalizedLSTMdata['target'].value_counts().sort_index()
print(target_dist)
print(f" % per class:")
target_pct = df_normalizedLSTMdata['target'].value_counts(normalize=True).sort_index() * 100
for idx, pct in target_pct.items():
    class_names = { 0: 'Down', 1: 'UP'}
    print(f"  {class_names[idx]:>4}: {pct:6.2f}%")

"""creating an last_target that would be used to know what appened before without leaking any Data"""

df_normalizedLSTMdata['last_target']= df_normalizedLSTMdata['target'].shift(1)

df_normalizedxgboostv2 = df_normalizedXGBoost.copy()

df_normalizedXGBoost

df_normalizedXGBoost['target'] = 0
threshold = 0.002
df_normalizedXGBoost['price_change'] = df_normalizedXGBoost['close'].diff()

df_normalizedXGBoost['target'] = np.where(df_normalizedXGBoost['price_change'] > threshold * df_normalizedXGBoost['close'].shift(1), 1,
                            np.where(df_normalizedXGBoost['price_change'] < -threshold * df_normalizedXGBoost['close'].shift(1), -1, 0))

# Drop the temporary 'price_change' column
df_normalizedXGBoost = df_normalizedXGBoost.drop('price_change', axis=1)

# Handle the first row which will have NaN for price_change
df_normalizedXGBoost['target'] = df_normalizedXGBoost['target'].fillna(0)

df_normalizedxgboostv2['target']= np.where(df_normalizedxgboostv2['close'] > df_normalizedxgboostv2['close'].shift(1), 1,0)

"""I will drop them so the model will not Use the current values to predict them but the lagged ones"""

df_normalizedXGBoost = df_normalizedXGBoost.drop('close', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('day_var_range', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('day_diff', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('volume', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('Bband_width', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('ADX', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('APO', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('CCI', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('MACD_Signal', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('MACD_Hist', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('SlowD', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('OBV', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('WMA', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('ATR', axis=1)
df_normalizedXGBoost = df_normalizedXGBoost.drop('RSI', axis=1)

df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('close', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('day_var_range', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('day_diff', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('volume', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('Bband_width', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('ADX', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('APO', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('CCI', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('MACD_Signal', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('MACD_Hist', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('SlowD', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('OBV', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('WMA', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('ATR', axis=1)
df_normalizedxgboostv2 = df_normalizedxgboostv2.drop('RSI', axis=1)

df_normalizedLSTMdata['last_target'] = df_normalizedLSTMdata['last_target'].fillna(0)

"""export the dataset to finish"""



LSTMpath = current_dir.parent.parent / "csv" / "Google"/ "LSTMdata.csv"
XGBoostpath = current_dir.parent.parent / "csv" / "Google"/ "XGBoostdata.csv"
XGBoostv2path = current_dir.parent.parent / "csv" / "Google"/ "xgboostv2.csv"



df_normalizedLSTMdata.to_csv(LSTMpath, index=False)
df_normalizedXGBoost.to_csv(XGBoostpath, index=False)
df_normalizedxgboostv2.to_csv(XGBoostv2path, index=False)