# -*- coding: utf-8 -*-
"""collectprice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJNBTFmg524lB50Hjl7GZgOCU_JNYHya
"""

import pandas as pd
import requests
import json
from pathlib import Path
from dotenv import load_dotenv
import os


load_dotenv()
Api_key = os.getenv("API_KEY1")
symbol = "NVDA"
interval = "daily"
time_period = "5"
series_type = "close"
maturity="15year"
outputsize = "full"
current_dir = Path(__file__).parent

def retriveOCLHV( symbol : str,outputsize:str, Api_key : str  ) ->dict:
  url = f"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&outputsize={outputsize}&interval=daily&apikey={Api_key}"
  response = requests.get(url)
  data = response.text
  parsedata = json.loads(data)
  return parsedata

try :
  data0 =retriveOCLHV(symbol,outputsize , Api_key)
  time_series = data0["Time Series (Daily)"]
  df_price= pd.DataFrame.from_dict(time_series, orient="index")
  df_price.columns = ["open", "high", "low", "close", "volume"]

  df_price.index = pd.to_datetime(df_price.index)
  df_price.index.name = 'date'

  #convert values from string to float :
  df_price["open"] = pd.to_numeric(df_price["open"], errors="coerce")
  df_price =df_price.drop(columns=["close", "high", "low","volume"])


  df_price = df_price.sort_index()

  df_price['open'] = df_price['open'].interpolate(method='time')



  # if their is still NAN at the extremities we fill them
  df_price['open'] = df_price['open'].fillna(method='bfill').fillna(method='ffill')

  csv_folder = current_dir.parent.parent / "csv" / "Nvidia"
  csv_folder.mkdir(parents=True, exist_ok=True)
  savecsv = csv_folder / "Nvidia_prices.csv"

  df_price.to_csv(savecsv, index = True)
except :
  print("API Error")
else:
  print("Execution succsesful")